### ISSUE TITLE
Freeze after ~10 minutes

### ISSUE THREAD

**Issue by iTrooz** [ShayBox/Mon2Cam#57] opened 2020-12-13 13:56 UTC
Hi ! I'm using manjaro with kernel 58, and when I launch mon2cam, the "screenshare" stop after roughly 10 minutes
Here is the verbose logs, but I don't think there is something important!
[test.png](https://user-images.githubusercontent.com/42669835/102013907-48ecf200-3d53-11eb-8a8b-4d185665ffb9.png)
(The program doesn't crash)

**Comment by ShayBox** [comment] 2020-12-13 14:00
Yeah I've been getting this since the rewrite but nothing indicates any changes when it freezes, and nobody else was reporting it, could you provide a full log (you don't have to wait for it to freeze), and what gpu and monitor refreshrate do you have.

EDIT: Why is your log small enough to fit in a single picture... interesting

**Comment by iTrooz** [comment] 2020-12-13 15:12
Here are my refresh rate 
![test](https://user-images.githubusercontent.com/42669835/102015766-c3227400-3d5d-11eb-89ec-6da60de7da29.png)
and my gpu is a GeForce GTX 1060
How can I provide a "full log" ?

**Comment by HorizonCode** [comment] 2020-12-15 13:19
same issue here :/

**Comment by devcexx** [comment] 2020-12-16 22:28
I'm having pretty much the same issue. Please let me know how can we help you to identify the root cause, I'll be glad to help on this :P.

**Comment by Rdeisenroth** [comment] 2020-12-18 11:09
Im also having the same freezing issue...
My current "workaround" until it's fixed is to automatically restart the program every two minutes:
`while true; do timeout 120s mon2cam --monitor 0;date ; sleep .3; done`
(the small delay here is used to be able to use CTRL+C to exit out of the loop)

**Comment by x10an14** [comment] 2020-12-26 11:04
I've got the same issue here - (timeout after ~10 minutes). @ShayBox please advice on how to further help you debug/figure this out! =)

<details>
<summary>My Linux info</summary>

```
[2020-12-26 12:18:01] 0 x10an14@x10-desktop:~
-> $ screenfetch 
         _,met$$$$$gg.           x10an14@x10-desktop
      ,g$$$$$$$$$$$$$$$P.        OS: Debian 10 buster
    ,g$$P""       """Y$$.".      Kernel: x86_64 Linux 4.19.0-13-amd64
   ,$$P'              `$$$.      Uptime: 22h 7m
  ',$$P       ,ggs.     `$$b:    Packages: 3866
  `d$$'     ,$P"'   .    $$$     Shell: bash 5.0.3
   $$P      d$'     ,    $$P     Resolution: 6560x2560
   $$:      $$.   -    ,d$$'     WM: i3
   $$\;      Y$b._   _,d$P'      CPU: AMD Ryzen 5 2600 Six-Core @ 12x 3.698GHz [48.0°C]
   Y$$.    `.`"Y$$$$P"'          GPU: GeForce GTX 1080
   `$$b      "-.__               RAM: 9230MiB / 32161MiB
    `Y$$                        
     `Y$$.                      
       `$$b.                    
         `Y$$b.                 
            `"Y$b._             
                `""""           
                                
[2020-12-26 12:18:10] 0 x10an14@x10-desktop:~
-> $ 
```

</detail>

**Comment by ShayBox** [comment] 2020-12-26 20:37
I really have no idea, no way to debug this, nothing is breaking

**Comment by iTrooz** [comment] 2020-12-26 20:38
Okay, so.. The hunt is open for us

**Comment by ShayBox** [comment] 2020-12-26 20:41
If you can find what's going on go ahead, but nothing is different from the bash script, ffmpeg or v4l2 is just breaking but not erroring

**Comment by GamerGuy95953** [comment] 2021-01-26 19:51
I am also having this same problem and also running manjaro. I know its v4l2 or ffmpeg but I'm just saying for anyone else to know it's not just them.

**Comment by GamerGuy95953** [comment] 2021-01-26 20:42
> Im also having the same freezing issue...
> My current "workaround" until it's fixed is to automatically restart the program every two minutes:
> `while true; do timeout 120s mon2cam --monitor 0;date ; sleep .3; done`
> (the small delay here is used to be able to use CTRL+C to exit out of the loop)

I tried your command on Linux manjaro cinnamon and it just says "INFO x11 detected, to use Wayland add -w". I tried seeing the preview but it's just blank.

EDIT: Nevermind i got it working by doing `sudo su` then the command.

**Comment by manugame** [comment] 2021-01-29 20:38
if you set framerate to 30, its doesn't freeze

**Comment by iTrooz** [comment] 2021-02-04 20:27
Sadly, even with this I get the freeze (is it the `-f 30` flag ?)

**Comment by bruno-novo-it** [comment] 2021-02-10 23:39
Hi, 

@iTrooz,  i run like this **mon2cam -f 30 --monitor 0 -x** and doesn't freeze even after one hour sharing the screen in Discord. Can you try this to see if it work's?

**Comment by iTrooz** [comment] 2021-02-15 16:25
Yep, and still freeze. Thanks for the help anyways

**Comment by solonovamax** [comment] 2021-03-20 18:31
> if you set framerate to 30, its doesn't freeze

>i run like this mon2cam -f 30 --monitor 0 -x and doesn't freeze even after one hour sharing the screen in Discord. Can you try this to see if it work's?

Even with the framerate at 30 fps, it still freezes for me.
I'm currently running it with `mon2cam -x -e -f 30 -m 0 -r 1280:720`, and it still seems to freeze for me.

**Comment by D3SOX** [comment] 2021-03-21 11:47
I don't know why but it doesn't freeze for me with `mon2cam -m 0 -f 29 -v`
The `-v` seems to be important for it not to freeze

**Comment by solonovamax** [comment] 2021-03-22 16:50
> I don't know why but doesn't freeze for me with mon2cam -m 0 -f 29 -v
The -v seems to be important for it not to freeze

I just tested that out, and I mirrored your results. I ran `mon2cam -x -e -f 30 -m 0 -r 1280:720 -v` for about 40 minutes, without the stream pausing. Not sure why when it's run in verbose mode it works, but when run in normal mode, it doesn't.... That's pretty strange.

**Comment by D3SOX** [comment] 2021-03-22 18:16
Maybe somehow the verbose mode keeps the ffmpeg process alive which would otherwise be killed after some time (still not sure why)

**Comment by ShayBox** [comment] 2021-03-23 01:11
That is pretty strange, thanks for discovering this

**Comment by devcexx** [comment] 2021-03-23 01:29
It seems that the stderr stream isn't read unless the verbose flag is set, but that descriptor is still redirected throught a pipe. If ffmpeg is writing to the stderr (actually it does everytime it prints the conversion progress), but there's no consumer reading from the pipe, it might happen that the pipe gets filled in a few minutes and any syscall to write to stderr would make the caller thread to sleep indefinitely, and might explain why ffmpeg stops responding after some time. Does it make any sense?

**Comment by GamerGuy95953** [comment] 2021-03-23 02:30
> I don't know why but doesn't freeze for me with `mon2cam -m 0 -f 29 -v`
> The `-v` seems to be important for it not to freeze

Can confirm! Fixed my issue on Linux Manjaro Cinnamon. Thanks!

**Comment by botiapa** [comment] 2021-03-23 09:05
@ShayBox  Maybe we should redirect into /dev/null when in non verbose mode?

**Comment by devcexx** [comment] 2021-03-23 09:08
> @ShayBox Maybe we should redirect into /dev/null when in non verbose mode?

+ Would be great if people that is actively experiencing this issue can check if this is actually the problem (e.g attaching the GDB to the process and check the stack traces or anything useful)

**Comment by ShayBox** [comment] 2021-03-23 14:23
Yes this appears to be the problem, I left it running in verbose all night and it didn't freeze, I don't know what you mean about the gdb thing, you can modify the code if you want, im gonna add the redirecting to fix the problem

**Comment by D3SOX** [comment] 2021-03-23 14:38
I'm glad I discovered this. It was more or less accidental though. I had used the old bash version for a long time and wanted to test the new version again (especially because of the hardware acceleration, which works really well by the way. It runs much smoother with `-e vaapi` for me).
Then I just added the `-v` flag for testing, later I thought it is a bit too much output for me. So I removed it and noticed that the freezing happens again now.

I hope it helps to fix this problem soon. This issue is now open for quite some time.

**Comment by ShayBox** [comment] 2021-03-23 14:47
The fix should be pushed, re-running the script should now work! (if you're using the alias, on arch you need to re-build the package)

**Comment by D3SOX** [comment] 2021-03-23 14:53
> you need to re-build the package

Or you use a package manager that  tracks development packages
![image](https://user-images.githubusercontent.com/24937357/112166397-e2982b00-8bef-11eb-9393-64d7c8b7fd6e.png)
(`yay -Syu --devel` or `paru`)

**Comment by D3SOX** [comment] 2021-03-23 15:42
The problem still happens for me at 8fdd0c1

**Comment by ShayBox** [comment] 2021-03-23 16:07
Fixed now, forgot to invert a condition

**Comment by D3SOX** [comment] 2021-03-23 17:04
I can confirm that it works now!

**Comment by iTrooz** [comment] 2021-04-19 21:35
Works for me too ! I'll close the issue, thanks everyone :)

**Closed as completed** 2021-04-19 21:36 UTC
