### ISSUE TITLE
Sound feature confusing to use

### ISSUE THREAD

**Issue by rsubtil** [ShayBox/Mon2Cam#23] opened 2020-07-27 13:47 UTC
Hi, I just found out about this project, kudos for finding a way around proper streaming to Discord!

I realized there's a feature to reroute sound from apps to a sink, which is literally everything I've ever needed xD However, I don't know how to use it *(the part of selection windows to reroute sound)*, and I feel like the script could have some sort of instruction on how to supply those window names.

Thanks for your effort!

**Comment by botiapa** [comment] 2020-07-27 17:54
Hi, thanks for the info, I will add some instructions on how to use this feature.

In the meantime I added some error checking in f3cc10c which might be useful.

**Comment by botiapa** [comment] 2020-07-27 19:26
Okay, added clarification in the readme and in the script as well. Please note that when streaming, you won't be able to hear the streamed application, unless you listen into the virtual sink as well, but then you will hear **yourself as well**. I will try to find a fix for this (no promises).

If you still want to use the feature I'd be happy to help. If not, then the issue is closable.

**Closed as completed** 2020-07-27 21:35 UTC
